#!/usr/bin/env node
/**
 * Generates the secrets this app needs and writes them to .env.local if that
 * file doesn't already exist.
 *
 * It deliberately refuses to overwrite an existing .env.local: rotating
 * APP_ENCRYPTION_KEY makes every stored API key undecryptable, and doing that
 * silently would be a very bad afternoon.
 */

import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const target = path.join(process.cwd(), '.env.local');

const encryptionKey = randomBytes(32).toString('base64');
const setupCode = randomBytes(9).toString('base64url');

if (existsSync(target)) {
  console.log('\n.env.local already exists — not touching it.\n');
  console.log('If you need a fresh encryption key, here is one:\n');
  console.log(`  APP_ENCRYPTION_KEY=${encryptionKey}\n`);
  console.log('WARNING: changing this key makes every already-stored API key');
  console.log('unreadable. You would need to re-enter them in Settings.\n');
  process.exit(0);
}

const contents = `# Bluddian — local secrets. NEVER commit this file.
# Generated by \`npm run keygen\` on ${new Date().toISOString()}

# 32 bytes, base64. Encrypts the API keys you store in Settings (AES-256-GCM).
# Changing this makes previously stored keys unreadable.
APP_ENCRYPTION_KEY=${encryptionKey}

# Required at first-run setup, so a public deployment can't be claimed by a
# stranger who finds it before you do. Delete this line once you've signed up.
SETUP_CODE=${setupCode}

# Where the SQLite database lives.
DATABASE_PATH=./data/bluddian.db

# Set to 1 ONLY when running behind a reverse proxy you control (Caddy, nginx,
# Fly, Railway). It makes the rate limiter trust X-Forwarded-For, which is
# spoofable if nothing in front of you is rewriting it.
# TRUST_PROXY=1

# --- Optional: supply integration keys by environment instead of the UI. ---
# Environment values take priority over anything saved in Settings.
# ANTHROPIC_ADMIN_API_KEY=
# WHOP_API_KEY=
# WHOP_COMPANY_ID=
# WHOP_WEBHOOK_SECRET=
# SHOPIFY_SHOP_DOMAIN=
# SHOPIFY_ADMIN_TOKEN=
# SHOPIFY_WEBHOOK_SECRET=
`;

writeFileSync(target, contents, { mode: 0o600 });

console.log('\n  Wrote .env.local (mode 600)\n');
console.log(`  Setup code for your first sign-up:  ${setupCode}\n`);
console.log('  Next:  npm run dev   then open http://localhost:3000\n');
